version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_Update_Native_ConstructsProject
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_update_native_constructs.integrations:C4
  packages:
  - name: SIQA_Update_Native_ConstructsProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: project.siqa_update_native_constructs.integrations:C5
  packages:
  - name: SIQA_Update_Native_ConstructsProject
    version: "1.0"
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: project.siqa_update_native_constructs.integrations:Simple_Flow
  packages:
  - name: SIQA_Update_Native_ConstructsProject
    version: "1.0"
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: project.siqa_update_native_constructs.integrations:TryCatchFinally
  packages:
  - name: SIQA_Update_Native_ConstructsProject
    version: "1.0"
- serviceName: project.siqa_update_native_constructs.integrations:loop_Order_Details
  packages:
  - name: SIQA_Update_Native_ConstructsProject
    version: "1.0"
- serviceName: pub.string:concat
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: project.siqa_update_native_constructs.integrations:newDAF
  packages:
  - name: SIQA_Update_Native_ConstructsProject
    version: "1.0"
- serviceName: project.siqa_update_native_constructs.integrations:whileC
  packages:
  - name: SIQA_Update_Native_ConstructsProject
    version: "1.0"
configurationVariables:
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  jdbc.jdbcTestPool.expireTime: "60000"
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  jdbc.jdbcTestPool.spyenabled: "false"
  jdbc.jdbcTestPool.snoopenabled: "false"
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  jdbc.jdbcTestPool.useSSL: "false"
